CREATE DATABASE Spotify;
USE Spotify;
CREATE TABLE Role (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL
);
CREATE TABLE [User] (
    Id INT PRIMARY KEY IDENTITY(1,1),
    FullName NVARCHAR(50) NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    SurName NVARCHAR(50) NOT NULL,
    IsVerified BIT DEFAULT 0,
    RoleId INT NOT NULL,
    FOREIGN KEY (RoleId) REFERENCES Role(Id) ON DELETE SET NULL
);
CREATE TABLE Subscription (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL,
    Price INT NOT NULL CHECK (Price > 0),
    UserId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE
);
CREATE TABLE Album (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL,
    CreatedTime DATETIME DEFAULT GETDATE()
);
CREATE TABLE Song (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL,
    DurationMinutes INT NOT NULL CHECK (DurationMinutes > 0),
    UserId INT NOT NULL,
    AlbumId INT,
    CreatedTime DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE,
    FOREIGN KEY (AlbumId) REFERENCES Album(Id) ON DELETE SET NULL
);
CREATE TABLE Category (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL,
    CreatedTime DATETIME DEFAULT GETDATE()
);
CREATE TABLE SongCategory (
    Id INT PRIMARY KEY IDENTITY(1,1),
    SongId INT NOT NULL,
    CategoryId INT NOT NULL,
    FOREIGN KEY (SongId) REFERENCES Song(Id) ON DELETE CASCADE,
    FOREIGN KEY (CategoryId) REFERENCES Category(Id) ON DELETE CASCADE
);
CREATE TABLE AlbumSong (
    Id INT PRIMARY KEY IDENTITY(1,1),
    AlbumId INT NOT NULL,
    SongId INT NOT NULL,
    FOREIGN KEY (AlbumId) REFERENCES Album(Id) ON DELETE CASCADE,
    FOREIGN KEY (SongId) REFERENCES Song(Id) ON DELETE CASCADE
);
